services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goods_db
    volumes:
      - goods_data:/var/lib/postgresql/data
      - ./scripts/initdb.sql:/docker-entrypoint-initdb.d/1-initdb.sql
    command: ['postgres', '-c', 'wal_level=logical']
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  debezium:
    image: debezium/connect:2.7.3.Final
    ports:
      - 8083:8083
    depends_on:
         - kafka1
         - kafka2
         - kafka3
         - kafka4
         - db
    environment:
        - BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9092
        - GROUP_ID=1
        - CONFIG_STORAGE_TOPIC=debezium_configs
        - OFFSET_STORAGE_TOPIC=debezium_offsets
        - STATUS_STORAGE_TOPIC=debezium_statuses
  kafka1:
    image:  bitnami/kafka:3.9
    container_name: kafka1
    ports:
      - "29092:29092"
      - "9991:9991" # JMX port for monitoring
    volumes:
      - kafka1:/bitnami/kafka
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093,4@kafka4:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL_LOCALHOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka1:9092,EXTERNAL_LOCALHOST://localhost:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL_LOCALHOST:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CLIENT_LISTENER_NAME=EXTERNAL_LOCALHOST
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
      - KAFKA_KRAFT_CLUSTER_ID=fsdfkdsfkdsfsd
      - KAFKA_CFG_NUM_PARTITIONS=10
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  kafka2:
    image: bitnami/kafka:3.9
    container_name: kafka2
    ports:
      - "29093:29093"
      - "9992:9991" # JMX port for monitoring
    volumes:
      - kafka2:/bitnami/kafka
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093,4@kafka4:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL_LOCALHOST://:29093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka2:9092,EXTERNAL_LOCALHOST://localhost:29093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL_LOCALHOST:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CLIENT_LISTENER_NAME=EXTERNAL_LOCALHOST
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_KRAFT_CLUSTER_ID=fsdfkdsfkdsfsd
      - KAFKA_CFG_NUM_PARTITIONS=10
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  kafka3:
    image: bitnami/kafka:3.9
    container_name: kafka3
    ports:
      - "29094:29094"
      - "9993:9991" # JMX port for monitoring
    volumes:
      - kafka3:/bitnami/kafka
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093,4@kafka4:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL_LOCALHOST://:29094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka3:9092,EXTERNAL_LOCALHOST://localhost:29094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL_LOCALHOST:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CLIENT_LISTENER_NAME=EXTERNAL_LOCALHOST
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_KRAFT_CLUSTER_ID=fsdfkdsfkdsfsd
      - KAFKA_CFG_NUM_PARTITIONS=10
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  kafka4:
    image: bitnami/kafka:3.9
    container_name: kafka4
    ports:
      - "29095:29095"
      - "9994:9991" # JMX port for monitoring
    volumes:
      - kafka4:/bitnami/kafka
    environment:
      - KAFKA_CFG_NODE_ID=4
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093,4@kafka4:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL_LOCALHOST://:29095
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka4:9092,EXTERNAL_LOCALHOST://localhost:29095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL_LOCALHOST:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CLIENT_LISTENER_NAME=EXTERNAL_LOCALHOST
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_CFG_NUM_PARTITIONS=10
      - KAFKA_KRAFT_CLUSTER_ID=fsdfkdsfkdsfsd
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8082:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
volumes:
  kafka1:
  kafka2:
  kafka3:
  kafka4:
  goods_data:
