version: '3.8'

services:
  nats1:
    image: nats:latest
    ports:
      - "4222:4222"        # основной порт для клиентов
      - "6222:6222"        # сервер мониторинга
      - "7422:7422"        # порт NGS (NATS Gateway)
    command: --debug --server_name nats1 --cluster nats://0.0.0.0:6222  --routes nats://nats2:6222,nats://nats3:6222 --cluster_name kk --store_dir /data
    volumes:
      - nats-data1:/data
  nats2:
    image: nats:latest
    ports:
      - "4223:4222"
      - "6223:6222"
      - "7423:7422"
    command: --debug  --server_name nats2 --cluster nats://0.0.0.0:6222  --routes nats://nats1:6222,nats://nats3:6222 --cluster_name kk --store_dir /data
    volumes:
      - nats-data2:/data
  nats3:
    image: nats:latest
    ports:
      - "4224:4222"
      - "6224:6222"
      - "7424:7422"
    command: --debug  --server_name nats3 --cluster nats://0.0.0.0:6222  --routes nats://nats1:6222,nats://nats2:6222 --cluster_name kk --store_dir /data
    volumes:
      - nats-data3:/data
volumes:
  nats-data1:
  nats-data2:
  nats-data3: